NumPy offers powerful shortcuts to create arrays without loops!

In [1]:
import numpy as np

In [2]:
a = np.zeros((3, 3))  # 3x3 array of zeros
b = np.ones((2, 4))   # 2x4 array of ones
c = np.full((2, 2), 7) # 2x2 array filled with 7
d = np.eye(4)          ## 4x4 identity matrix
e = np.arange(1, 10, 2) # [1, 3, 5, 7, 9] (like range)
f = np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

In [3]:
print("{a}{b}{c}{d}{e}{f}")

{a}{b}{c}{d}{e}{f}


In [4]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Shape:", arr.shape) # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size) #6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array 
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


Changing Data type of array

In [5]:
arr2 = np.array([1, 2, 3], dtype=np.float32) # Explicit type
print(arr2.dtype) # float32
arr_int = arr2.astype(np.int32) # Convert float to int
print(arr_int) # [1 2 3]

float32
[1 2 3]


Reshaping  & Flattening Array

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("This is the shape of array : " ,arr.shape)

reshaped = arr.reshape((3, 2)) # Change shape
print("\n\nThis is Reshaped Array")
print(reshaped)
print("Now this is a Reshaped Array & Shape of array is :- ", reshaped.shape)

flattened = arr.flatten() # Convert 2D → 1D
print("\n",flattened) # [1 2 3 4 5 6]
print("Now we have Converted 2-D Array to 1-D Array.\nShape of Array :- ",flattened.shape)

[[1 2 3]
 [4 5 6]]
This is the shape of array :  (2, 3)


This is Reshaped Array
[[1 2]
 [3 4]
 [5 6]]
Now this is a Reshaped Array & Shape of array is :-  (3, 2)

 [1 2 3 4 5 6]
Now we have Converted 2-D Array to 1-D Array.
Shape of Array :-  (6,)
