In [1]:
import numpy as np

<h3>Indexing <span background-color="yellow">(Same as Python Lists)</span></h3>
<p>Starts from '0'</p>    

In [2]:
arr = np.array([10, 20, 30, 40])
print(arr[0]) # 10
print(arr[-1]) # 4

10
40


In [4]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) # [20 30 40]   (slice from index 1 to 3)
print(arr[:3]) # [10 20 30]    (first 3 elements)
print(arr[::2]) # [10 30 50]   (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


<b>Slicing returns a view, not a copy! Changes affect the original
array.<b>

<h3>Fancy Indexing </h3>

In [5]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4] # Indices to select
print(arr[idx]) # [10 30 50]

[10 30 50]


<h3>Boolean Masking</h3>
<b>This is a powerful way to filter large datasets efficiently!</b>

In [7]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25 # Condition: values greater than 25
print(arr[mask]) # [30 40 50]

[30 40 50]
